# A Guided Tour of Ray Core: Remote Tasks

© 2019-2022, Anyscale. All Rights Reserved

### Learning objectives
In this this tutorial, we revist Ray task and learn about:
 * Remote Task Parallel Pattern
 * Stateless remote functions as distributed tasks
 * Serial vs Parallel execution 
 * Understand the concept of a Ray task 
 * Easy API to convert an existing Python function into a Ray remote task
 
<img src="images/ray_basic_patterns.png" height="35%" width="60%">

In [5]:
import os
import time
import logging
from pprint import pprint

import numpy as np
from numpy import loadtxt
import ray

## 1. Tasks Parallel Pattern

Ray converts decorated functions into stateless tasks, scheduled anywhere on a Ray worker in the cluster by simply adding the `@ray.remote` decorator. 
All these decorated Pythohn functions are converted into Ray stateless tasks and will be scheduled and executed on some worker process on a node in the 
Ray cluster.

Where they will be executed (and by whom), you don't have to worry about its details. All that is taken care for you. Nor do 
you have to reason about it — all that burden is Ray's job. You simply take your existing Python functions and covert them into 
distributed stateless *Ray Tasks*: **as simple as that!**

### Example 1: Serial vs Parallelism

Let's look at simple tasks running serially and then in parallel. For illustration, we'll use a simple task, but this could be a compute-intensive task as part of your workload.


In [6]:
# A regular Python function.
def regular_function():
    return 1

In [7]:
# A Ray remote function.
@ray.remote
def remote_function():
    return 1

There are a few key differences between the original function and the decorated one:

**Invocation**: The regular version is called with `regular_function()`, whereas the remote version is called with `remote_function.remote()`. Keep this pattern in mind for all Ray remote execution methods.

**Return values**: `regular_function` executes synchronously and returns the result of the function as the value `1'`, whereas `remote_function` immediately returns an `ObjectID` (a future) and then executes the task in the background on a remote worker process. The result of the future can be obtained by calling `ray.get` on the `ObjectID`. This is a blocking function.

In [8]:
# Let's invoke the regular function
regular_function()

1

Let's launch a Ray cluster on our local machine. This will run a headnode.

In [9]:
if ray.is_initialized:
    ray.shutdown()
context = ray.init(logging_level=logging.ERROR)
pprint(context)

RayContext(dashboard_url='127.0.0.1:8265', python_version='3.8.13', ray_version='1.13.0', ray_commit='e4ce38d001dbbe09cd21c497fedd03d692b2be3e', address_info={'node_ip_address': '127.0.0.1', 'raylet_ip_address': '127.0.0.1', 'redis_address': None, 'object_store_address': '/tmp/ray/session_2022-07-15_09-55-13_287676_16181/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2022-07-15_09-55-13_287676_16181/sockets/raylet', 'webui_url': '127.0.0.1:8265', 'session_dir': '/tmp/ray/session_2022-07-15_09-55-13_287676_16181', 'metrics_export_port': 61412, 'gcs_address': '127.0.0.1:65516', 'address': '127.0.0.1:65516', 'node_id': '6a39c46bba59fa4e86cb773569dfd4a4989a35ef68fd23fa77f07f77'})


In [11]:
print(f"Dashboard url: http://{context.address_info['webui_url']}")

Dashboard url: http://127.0.0.1:8265


In [12]:
# Let's invoke the remote regular function.
remote_function.remote()

ObjectRef(c8ef45ccd0112571ffffffffffffffffffffffff0100000001000000)

In [13]:
ray.get(remote_function.remote())

1

**No Parallelism**: Invocations of `regular_function` in a loop happen `serially`:

In [14]:
# These are executed one at a time, back-to-back, in a list comprehension
results = [regular_function() for _ in range(10)]
assert sum(results) == 10

**Parallelism**: Invocations of `remote_function` in a loop happen `asynchronously` and in parallel:

In [15]:
# Executing these functions, in comprehension list, happens at the same time in the background, 
# and we get the results using ray.get.
results = [remote_function.remote() for _ in range(10)]
assert sum(ray.get(results)) == 10

### Example 2: Adding two np arrays

<img src="images/task_api_add_array.png" width="60%" height="40%">

Define a function as a Ray task to read an array

In [16]:
@ray.remote
def read_array(fn: str) -> np.array:
    arr = loadtxt(fn, comments="#", delimiter=",", unpack=False)
    return arr.astype('int')

Define a function as a Ray task to add two np arrays return the sum

In [17]:
@ray.remote
def add_array(arr1: np.array, arr2: np.array) -> np.array:
    return np.add(arr1, arr1)

Define a function as a Ray task to sum the contents of an np array

In [18]:
@ray.remote
def sum_array(arr1: np.array) -> int:
    return np.sum(arr1)

Now let's execute our tasks. For now we will run Ray locally on our laptop, with a single node, and use all the cores available.

Ray executes immediately and returns an object reference `ObjectRef` as a future. This enables Ray to parallelize tasks and execute them asynchronously.

### Read both arrays. 

Use the `func_name.remote(args)` extention to invoke a remote Ray Task

In [19]:
obj_ref_arr1 = read_array.remote(os.path.abspath("data/file_1.txt"))
print(f"array 1: {obj_ref_arr1}")

array 1: ObjectRef(85748392bcd969ccffffffffffffffffffffffff0100000001000000)


In [20]:
obj_ref_arr2 = read_array.remote(os.path.abspath("data/file_2.txt"))
print(f"array 2: {obj_ref_arr2}")

array 2: ObjectRef(d695f922effe6d99ffffffffffffffffffffffff0100000001000000)


### Add both arrays

Let's add our two arrays by calling the remote method. *Note*: We are sending Ray `ObjectRef` references as arguments.Those will be resolved inline and fetched from owner. Note that node that creates the ref owns them and stores it in its object store. 

Ray scheduler is aware of where these object references reside or who owns them, so it will schedule this remote task on node on the worker process for data locality.

In [21]:
result_obj_ref = add_array.remote(obj_ref_arr1, obj_ref_arr2)
result_obj_ref

ObjectRef(2751d69548dba956ffffffffffffffffffffffff0100000001000000)

### Fetch the result 

This will block if not finished

In [22]:
result = ray.get(result_obj_ref)
print(f"Result: add arr1 + arr2: \n {result}")

Result: add arr1 + arr2: 
 [[  0  96 144 150 108 178 168 136  18  76]
 [  6  80 146 116  20  70 192  12 130  66]
 [110 134  24 194 104 146  14 152  78 100]
 [118  68  40  80 184 110  22  78 186  76]
 [178 178  74 104  96 172  98   6  38 100]
 [168  74 136  22  40  72  92 122 104 154]
 [140 180 112 110  98 152 188  56  64  46]
 [ 10  88 184  30 106 126 174 150 122  50]
 [102 116  58  60 186 188 104 144 160  54]
 [  2  56 164  70 178  72  20 168 170 130]]


Add the array elements and get the sum
Note we are sending objRefs as arguments to the function
Ray will resolve or fetch the value of these arrays. 

In [23]:
sum_1 = ray.get(sum_array.remote(obj_ref_arr1))
sum_2 = ray.get(sum_array.remote(obj_ref_arr2))

In [24]:
print(f'Sum of arr1: {sum_1}')
print(f'Sum of arr2: {sum_2}')

Sum of arr1: 5173
Sum of arr2: 7719


### Example 3: Generating Fibonnaci series

Let's define two functions: one runs locally or serially, the other runs on a Ray cluster (local or remote). This example is borrowed and refactored from our 
blog: [Writing your First Distributed Python Application with Ray](https://www.anyscale.com/blog/writing-your-first-distributed-python-application-with-ray). 
(This is an excellent tutorial to get started with the concept of why and when to use Ray tasks and Ray Actors. Highly recommended read!)

Another similar blog of interest is how to compute the value of **pi**: [How to scale Python multiprocessing to a cluster with one line of code](https://medium.com/distributed-computing-with-ray/how-to-scale-python-multiprocessing-to-a-cluster-with-one-line-of-code-d19f242f60ff).

In [25]:
# Local execution 
def generate_fibonacci(sequence_size):
    fibonacci = []
    for i in range(0, sequence_size):
        if i < 2:
            fibonacci.append(i)
            continue
        fibonacci.append(fibonacci[i-1]+fibonacci[i-2])
    return len(fibonacci)

In [26]:
# Remote Task with just a wrapper
@ray.remote
def generate_fibonacci_distributed(sequence_size):
    return generate_fibonacci(sequence_size)

In [27]:
# Get the number of cores 
os.cpu_count()

10

In [28]:
# Normal Python in a single process 
def run_local(sequence_size):
    results = [generate_fibonacci(sequence_size) for _ in range(os.cpu_count())]
    return results

In [29]:
%%time
run_local(100000)

CPU times: user 1.51 s, sys: 411 ms, total: 1.92 s
Wall time: 1.92 s


[100000,
 100000,
 100000,
 100000,
 100000,
 100000,
 100000,
 100000,
 100000,
 100000]

In [30]:
# Distributed on a Ray cluster
def run_remote(sequence_size):
    results = ray.get([generate_fibonacci_distributed.remote(sequence_size) for _ in range(os.cpu_count())])
    return results

In [31]:
%%time
run_remote(100000)

CPU times: user 10.9 ms, sys: 6.61 ms, total: 17.5 ms
Wall time: 365 ms


[100000,
 100000,
 100000,
 100000,
 100000,
 100000,
 100000,
 100000,
 100000,
 100000]

### Concept of Task Dependencies

Consider the following basic remote function that returns the argument passed to it. If we pass in some normal Python objects, the results 
returned by `ray.get` should be the same objects.

In [32]:
@ray.remote
def f(x):
    return x

x1_id = f.remote(1)
ray.get(x1_id)

1

In [33]:
x2_id = f.remote([1, 2, 3])
ray.get(x2_id)

[1, 2, 3]

However, `object IDs` can also be passed into remote functions. When the function is executed, Ray will automatically substitute the underlying Python object that the object ID refers to. In a sense, it's the same as calling `ray.get` on each argument that's passed in as an argument.

In [34]:
y1_id = f.remote(x1_id)
ray.get(y1_id)

1

In [35]:
y2_id = f.remote(x2_id)
ray.get(y2_id)

[1, 2, 3]

**NOTE**: When implementing a remote function, the function should expect a regular Python object regardless of whether the caller passes in a regular Python object or an object ID.

**These task dependencies affect scheduling**. In the example above, the task that creates `y1_id` depends on the task that creates `x1_id`. This means that:

 * The second task will not be executed until the first task has finished executing.
 * If the two tasks are scheduled on different machines, the output of the first task (the value corresponding to x1_id) will be copied over the network to the machine where the second task is scheduled.

### Example 4: Task Dependencies: Aggregating Values Efficiently

Task dependencies can be used in much more sophisticated ways. For example, suppose we wish to aggregate 8 values together. This example uses naive integer addition, but in many applications, aggregating large vectors across multiple machines can be a bottleneck. In this case, changing a single line of code can change the aggregation’s running time from linear to logarithmic in the number of values being aggregated.

<img src="images/task_dependencies_graphs.png" height="50%" width="70%">

In [36]:
# define a task to add two intergers
@ray.remote
def add(x, y):
    time.sleep(1)
    return x + y

#### Add values the slow approach

In [37]:
values = [i for i in range(1, 9)]
values

[1, 2, 3, 4, 5, 6, 7, 8]

In [38]:
%%time

while len(values) > 1:
    values = [add.remote(values[0], values[1])] + values[2:]
    print(values)
result = ray.get(values[0])
print(result)

[ObjectRef(79cc316456d39201ffffffffffffffffffffffff0100000001000000), 3, 4, 5, 6, 7, 8]
[ObjectRef(c1464dc5b2308f10ffffffffffffffffffffffff0100000001000000), 4, 5, 6, 7, 8]
[ObjectRef(c5db14a0419b947bffffffffffffffffffffffff0100000001000000), 5, 6, 7, 8]
[ObjectRef(91581beb08e6c9deffffffffffffffffffffffff0100000001000000), 6, 7, 8]
[ObjectRef(ae46b8beecd25f3affffffffffffffffffffffff0100000001000000), 7, 8]
[ObjectRef(aa3d5d11e415fe88ffffffffffffffffffffffff0100000001000000), 8]
[ObjectRef(a6d6d59239756144ffffffffffffffffffffffff0100000001000000)]
36
CPU times: user 48.4 ms, sys: 31.7 ms, total: 80.1 ms
Wall time: 7.07 s


#### Add values the faster approach

In [39]:
%%time

while len(values) > 1:
    values = values[2:] + [add.remote(values[0], values[1])]
result = ray.get(values[0])
print(result)

36
CPU times: user 1.26 ms, sys: 349 µs, total: 1.61 ms
Wall time: 1.33 ms


In [40]:
# Normally will want to shutdown
ray.shutdown()

---

### Exercises

1. Increase the fibonacci with 200K, 300K
2. Add a compute intensive function; pick some function from your repo.
3. [Optional] Try running how to [compute PI](extra/highly_arallel.ipynb). **Note**: You can tweak with the `FULL_SAMPLE_COUNT`, to adjust the accuracy to the value of `math.pi`. `100 billion samples` may take too long. Play with number.

### Homework
1. Try adding local [bubble sort](https://www.geeksforgeeks.org/python-program-for-bubble-sort/) and remote bubble sort
2. Do you see the difference for small and large numbers?
3. Read this [blog](https://www.anyscale.com/blog/parallelizing-python-code) and try some examples.

### References

1. [Modern Parallel and Distributed Python: A Quick Tutorial on Ray](https://towardsdatascience.com/modern-parallel-and-distributed-python-a-quick-tutorial-on-ray-99f8d70369b8) by Robert Nishihara, co-creator of Ray and co-founder Anyscale
2. [Ray Core Introduction](https://www.anyscale.com/events/2022/02/03/introduction-to-ray-core-and-its-ecosystem) by Jules S. Damji